### ISSUE TITLE
Excuse me,when will the code be open sourced？

### ISSUE THREAD

**Issue by hushuai1** [sunny2109/ShuffleMixer#1]

**Comment by sunny2109** [comment]
Thanks for your interest, we will release the code around June 20th.

**Comment by cendelian** [comment]
> Thanks for your interest, we will release the code around June 20th.

where is code? thanks

**Comment by dylan2187** [comment]
同求，谢谢~

**Comment by sunny2109** [comment]
@dylan2187 实在不好意思，由于后续工作还在进行中，代码会推迟一段时间公开。如果您需要在测试集上的结果，我可以发给您。

**Comment by dylan2187** [comment]
好的，麻烦您了发给我一下吧，感谢~~这项工作非常好，我很期待！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sunny2109/ShuffleMixer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月29日(星期三) 晚上11:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [sunny2109/ShuffleMixer] Excuse me,when will the code be open sourced？ (Issue #1)





 
@dylan2187 实在不好意思，由于后续工作还在进行中，代码会推迟一段时间公开。如果您需要在测试集上的结果，我可以发给您。

**Comment by sunny2109** [comment]
@dylan2187 麻烦留个邮箱，我晚上发给您。

**Comment by dylan2187** [comment]
***@***.***





------------------ Original ------------------
From: sunny2109 ***@***.***&gt;
Date: Thu,Jun 30,2022 3:39 PM
To: sunny2109/ShuffleMixer ***@***.***&gt;
Cc: Dylan ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [sunny2109/ShuffleMixer] Excuse me,when will the code be open sourced？ (Issue #1)





 
@dylan2187 麻烦留个邮箱，我晚上发给您。

**Comment by sunny2109** [comment]
@dylan2187 邮箱好像被屏蔽了，我发我的邮箱吧：cs[dot]longsun[at]gmail[dot]com。
