### ISSUE TITLE
Keyerror: "No object named 'ShuffleMixer' found in 'arch' registry!"

### ISSUE THREAD

**Issue by DongmingYuu** [sunny2109/ShuffleMixer#4]
Thank you so much for your work. Your code is based on 'Basicsr', but when I run the code I found that there's no shufflemixer in arch registered. I've already update my basicsr library to the latest version. I wonder how I can train a Shufflemixer network under such condition? Thank you!

**Comment by sunny2109** [comment]
Thanks for your interest, please follow the below steps to install the ShuffleMixer.

```
# Clone the repo
git clone https://github.com/sunny2109/ShuffleMixer.git
# Install dependent packages
cd ShuffleMixer
pip install -r requirements.txt
# Install BasicSR
python setup.py develop
```

**Comment by DongmingYuu** [comment]
> Thanks for your interest, please follow the below steps to install the ShuffleMixer.
> 
> ```
> # Clone the repo
> git clone https://github.com/sunny2109/ShuffleMixer.git
> # Install dependent packages
> cd ShuffleMixer
> pip install -r requirements.txt
> # Install BasicSR
> python setup.py develop
> ```

Thank you so much! I should've read it more carefully. I thought all I needed was just 'pip install basicsr'. Thanks a lot for your prompt reply!
